script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'

git:
  depth: 1

sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - build-essential
    - git
    - fakeroot
